# Generated by Django 5.2.17 on 2026-09-16 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('consulta', models.CharField(help_text='Parámetros de la URL de búsqueda.', max_length=500)),
                ('icono', models.CharField(default='🔎', max_length=8)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Búsqueda guardada',
                'verbose_name_plural': 'Búsquedas guardadas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No'), ('moneda', 'Importe'), ('url', 'Enlace'), ('seleccion', 'Lista de opciones')], default='texto', max_length=16)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Solo para listas de opciones.')),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Corresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190, unique=True)),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Corresponsales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('nivel', models.CharField(default='info', max_length=10)),
                ('mensaje', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registro',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190, unique=True)),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('color', models.CharField(default='#8a8f98', max_length=7)),
                ('inbox', models.BooleanField(default=False, help_text='Se asigna automáticamente a lo que llega por el buzón.', verbose_name='Es bandeja de entrada')),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='biblioteca.etiqueta')),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ruta', models.CharField(help_text='Ruta relativa a la carpeta de biblioteca.', max_length=1000, unique=True)),
                ('hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bytes', models.BigIntegerField(default=0)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha del documento')),
                ('anadido', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('mtime', models.FloatField(default=0.0, help_text='Marca de tiempo del fichero en disco.')),
                ('abierto', models.DateTimeField(blank=True, null=True, verbose_name='Visto por última vez')),
                ('notas', models.TextField(blank=True)),
                ('favorito', models.BooleanField(default=False)),
                ('papelera', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ok', 'Correcto'), ('ausente', 'Fichero ausente'), ('cambiado', 'Cambiado en disco')], default='ok', max_length=10)),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('corresponsal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='biblioteca.corresponsal')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='documentos', to='biblioteca.etiqueta')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='biblioteca.tipodocumento')),
            ],
            options={
                'ordering': ['-anadido'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='biblioteca.campopersonalizado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='biblioteca.documento')),
            ],
            options={
                'verbose_name': 'Valor de campo',
                'verbose_name_plural': 'Valores de campo',
            },
        ),
        migrations.AddConstraint(
            model_name='etiqueta',
            constraint=models.UniqueConstraint(fields=('nombre', 'padre'), name='etiqueta_unica_por_padre'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['-fecha'], name='biblioteca__fecha_f4ba14_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['papelera', '-anadido'], name='biblioteca__papeler_7787e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='valorcampo',
            constraint=models.UniqueConstraint(fields=('documento', 'campo'), name='valor_unico_por_campo'),
        ),
    ]
