# Generated by Django 5.2.17 on 2026-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_indice_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='por_revisar',
            field=models.BooleanField(db_index=True, default=False, help_text='Lo ponen el buzón y la subida; se quita al catalogarlo.', verbose_name='Recién llegado, sin catalogar'),
        ),
    ]
